Fix cli script.
cli.py was not functional because of a failed relative import in yamlconfig:
Traceback (most recent call last):
  File "./cli.py", line 3, in <module>
    from yamlconfig import YamlConfig
  File "/..../yamlconfig/yamlconfig/yamlconfig.py", line 7, in <module>
    from . import yaml
ValueError: Attempted relative import in non-package

To fix it, yamlconfig is put in a src package.

Signed-off-by: Sebastien Fusilier <sebastien.fusilier@intel.com>